
FROM python:3.10-slim

LABEL maintainer="mingoemanuel07@gmail.com"


# Install system dependencies
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libgtk2.0-dev \
    cmake \
    build-essential \
    apache2-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /code/app

RUN mkdir uploads

EXPOSE 8000

 CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
# CMD ["sh", "-c", "mongod --fork --logpath /var/log/mongodb.log && uvicorn app.main:app --host 0.0.0.0 --port 8000"]
