version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ContainerFile
    container_name: image-processing-fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
      - ./uploads:/code/uploads
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
